version: "3.9"
services:

  ### Prefect Database
  database:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prefect
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
    profiles: [ "server" ]

  ### Prefect Server API and UI
  server:
    image: prefecthq/prefect:2.8.7-python3.11
    restart: always
    volumes:
      - prefect:/root/.prefect
    entrypoint: [ "prefect", "orion", "start" ]
    environment:
      # If you want to access Prefect Server from anywhere other than the Docker host machine, you will need to change
      # PREFECT_UI_URL to match the external hostname/IP used to load the  UI in your web browser.
      - PREFECT_UI_URL=http://127.0.0.0:4200/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@database:5432/prefect
    ports:
      - 4200:4200
    depends_on:
      - database
    profiles: [ "server" ]

  ## Prefect Agent
  agent:
    image: prefecthq/prefect:2.8.7-python3.11
    restart: always
    entrypoint:
      [
        "prefect",
        "agent",
        "start",
        "-q",
        "YOUR_WORK_QUEUE_NAME"
      ]
    environment:
      - PREFECT_API_URL=http://server:4200/api
    #       Use PREFECT_API_KEY if connecting the agent to Prefect Cloud
    #     - PREFECT_API_KEY=YOUR_API_KEY
    profiles: [ "agent" ]

  ### Prefect CLI
  cli:
    image: prefecthq/prefect:2.8.7-python3.11
    entrypoint: "bash"
    working_dir: "/root/flows"
    volumes:
      - "./flows:/root/flows"
    environment:
      - PREFECT_API_URL=http://server:4200/api
    #       Use PREFECT_API_KEY to use the CLI to interact with Prefect Cloud
    #     - PREFECT_API_KEY=YOUR_API_KEY
    profiles: [ "cli" ]

volumes:
  prefect:
  db:
  minio:
networks:
  default:
    name: prefect-network
