version: "3.7"
services:

  ### Prefect Database
  database:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prefect
    expose:
      - 5432
    volumes:
      - db_postgres:/var/lib/postgresql/data

  ### Prefect Server API and UI
  server:
    image: python_prefect_dbt
    restart: always
    volumes:
      - prefect:/root/.prefect
      - .:/root/github-data-pipeline
    entrypoint: [ "prefect", "orion", "start", "--host", "0.0.0.0" ]
    environment:
      - PREFECT_ORION_API_HOST=127.0.0.1
      - PREFECT_ORION_API_PORT=4200
      - PREFECT_API_URL=http://127.0.0.1:4200/api
      - PREFECT_ORION_UI_API_URL=http://${GCE_EXTERNAL_IP}:4200/api
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@database:5432/prefect
      - PREFECT_LOCAL_STORAGE_PATH="/root/github-data-pipeline"
    ports:
      - 4200:4200
    depends_on:
      - database

  ## Prefect Agent
  agent:
    image: python_prefect_dbt
    restart: always
    volumes:
      - .:/root/github-data-pipeline
    entrypoint: [ "prefect", "agent", "start", "-q", "default" ]
    environment:
      - PREFECT_API_URL=http://server:4200/api
      - PREFECT_LOCAL_STORAGE_PATH="/root/github-data-pipeline"

  # job
  job:
    image: python_prefect_dbt
    entrypoint: [ "python3" ]
    working_dir: "/root/github-data-pipeline"
    volumes:
      - .:/root/github-data-pipeline
    environment:
      - PREFECT_API_URL=http://server:4200/api
      - PREFECT_LOCAL_STORAGE_PATH="/root/github-data-pipeline"
volumes:
  prefect:
  db_postgres:
networks:
  default:
    name: prefect-network
