version: "3.7"
services:

  ### Prefect Database
  database:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    expose:
      - 5432
    volumes:
      - db_postgres:/var/lib/postgresql/data

  ### Prefect Server API and UI
  server:
    image: python_prefect_dbt
    restart: always
    volumes:
      - prefect:/root/.prefect
      - .:/root/github-data-pipeline
    entrypoint: [ "prefect", "orion", "start", "--host", "0.0.0.0" ]
    environment:
      - PREFECT_ORION_API_HOST=${PREFECT_ORION_API_HOST}
      - PREFECT_ORION_API_PORT=${PREFECT_ORION_API_PORT}
      - PREFECT_API_URL=${PREFECT_API_URL}
      - PREFECT_ORION_UI_API_URL=${PREFECT_ORION_UI_API_URL}
      - PREFECT_API_DATABASE_CONNECTION_URL=${PREFECT_API_DATABASE_CONNECTION_URL}
      - PREFECT_LOCAL_STORAGE_PATH=${PREFECT_LOCAL_STORAGE_PATH}
    ports:
      - 4200:4200
    depends_on:
      - database

  ## Prefect Agent
  agent:
    image: python_prefect_dbt
    restart: always
    volumes:
      - .:/root/github-data-pipeline
    entrypoint: [ "prefect", "agent", "start", "-q", "default" ]
    environment:
      - PREFECT_API_URL=http://server:4200/api
      - PREFECT_LOCAL_STORAGE_PATH=${PREFECT_LOCAL_STORAGE_PATH}

  # job
  job:
    image: python_prefect_dbt
    entrypoint: [ "python3" ]
    working_dir: ${PREFECT_LOCAL_STORAGE_PATH}
    volumes:
      - .:${PREFECT_LOCAL_STORAGE_PATH}
    environment:
      - PREFECT_API_URL=http://server:4200/api
      - PREFECT_LOCAL_STORAGE_PATH=${PREFECT_LOCAL_STORAGE_PATH}
volumes:
  prefect:
  db_postgres:
networks:
  default:
    name: prefect-network
