dbt_project_github:
  outputs:
    dev:
      type: bigquery
      dataset: dev_github
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /mnt/d/personal-github/github-data-pipeline/keys/sa-project.json
      location: asia-southeast1
      method: service-account
      priority: interactive
      project: dtc-de-zoomcamp-2023-376219
      threads: 1
    prod:
      type: bigquery
      dataset: prod_github
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /mnt/d/personal-github/github-data-pipeline/keys/sa-project.json
      location: asia-southeast1
      method: service-account
      priority: interactive
      project: dtc-de-zoomcamp-2023-376219
      threads: 1
  target: dev